package expo.modules.processor

import expo.modules.processor.OptimizedFunctionProcessor.FunctionMetadata

object KotlinRegistryGenerator {

    fun generate(moduleName: String, packageName: String, functions: List<FunctionMetadata>): String {
        val extensionFunctions = functions.joinToString("\n\n") { function ->
            val jniSignature = buildJNISignature(function)
            val paramTypesArray = function.parameters.joinToString(", ") {
                "\"${mapKotlinTypeToJNISignature(it.kotlinType)}\""
            }
            val returnType = mapKotlinTypeToJNISignature(function.returnType)

            """/**
 * Returns an optimized function descriptor for: ${function.kotlinFunctionName}
 *
 * Usage in ModuleDefinition: `Function("${function.kotlinFunctionName}", ${function.kotlinFunctionName}())`
 */
fun $packageName.${moduleName}.${function.kotlinFunctionName}(): expo.modules.kotlin.functions.OptimizedFunctionDescriptor {
    return expo.modules.kotlin.functions.OptimizedFunctionDescriptor(
        kotlinMethodName = "${function.kotlinFunctionName}",
        jniSignature = "$jniSignature",
        paramTypes = arrayOf($paramTypesArray),
        returnType = "$returnType"
    )
}"""
        }

        return """
// Generated by OptimizedFunctionProcessor
// DO NOT EDIT - This file is auto-generated

package $packageName

$extensionFunctions
""".trimIndent()
    }

    private fun buildJNISignature(metadata: FunctionMetadata): String {
        val paramSignatures = metadata.parameters.joinToString("") { param ->
            mapKotlinTypeToJNISignature(param.kotlinType)
        }
        val returnSignature = mapKotlinTypeToJNISignature(metadata.returnType)
        return "($paramSignatures)$returnSignature"
    }

    private fun mapKotlinTypeToJNISignature(kotlinType: String): String {
        return when (kotlinType) {
            "Double" -> "D"
            "Int" -> "I"
            "Boolean" -> "Z"
            "Long" -> "J"
            "Float" -> "F"
            "String" -> "Ljava/lang/String;"
            "Unit" -> "V"
            else -> "Ljava/lang/Object;"
        }
    }
}
